INSERT INTO cursos (nombre, categoria)
VALUES ('Python: fundamentos esenciales para principiantes', 'Programación'),
       ('Python: manejo de archivos, JSON y APIs', 'Programación'),
       ('Python Avanzado: programación orientada a objetos y patrones', 'Programación'),
       ('JavaScript: fundamentos y buenas prácticas', 'Programación'),
       ('JavaScript Avanzado: asincronía, promesas y fetch API', 'Programación'),
       ('Node.js: construyendo aplicaciones backend', 'Programación'),
       ('TypeScript: tipado estático en proyectos JavaScript', 'Programación'),
       ('C#: introducción al desarrollo con .NET', 'Programación'),
       ('SQL: consultas básicas y avanzadas en bases de datos', 'Programación'),
       ('Algoritmos y estructuras de datos: resolución de problemas', 'Programación'),
       ('React: crea interfaces interactivas con componentes', 'Front End'),
       ('React Avanzado: hooks, contexto y optimización de apps', 'Front End'),
       ('Angular: desarrollo de aplicaciones modernas', 'Front End'),
       ('Vue.js: fundamentos y ecosistema de Vue', 'Front End'),
       ('Bootstrap 5: diseño responsive rápido y efectivo', 'Front End'),
       ('Diseño UX/UI: principios para mejorar la experiencia de usuario', 'Front End'),
       ('Scrum: fundamentos para equipos ágiles', 'Innovación y Gestión'),
       ('Kanban: visualiza y mejora tu flujo de trabajo', 'Innovación y Gestión'),
       ('OKR: cómo definir y medir objetivos en tu empresa', 'Innovación y Gestión'),
       ('Liderazgo en equipos tecnológicos', 'Innovación y Gestión'),
       ('Gestión del tiempo: técnicas para aumentar productividad', 'Innovación y Gestión'),
       ('Introducción a la Ciberseguridad', 'DevOps'),
       ('Docker: crea y gestiona contenedores', 'DevOps'),
       ('Kubernetes: orquestación de contenedores', 'DevOps'),
       ('CI/CD: automatización de integración y despliegue', 'DevOps'),
       ('Linux: comandos básicos para desarrolladores', 'DevOps'),
       ('Cloud Computing: fundamentos de AWS, Azure y GCP', 'DevOps');
